### ISSUE TITLE
Cannot right click bags in latest updates

### ISSUE THREAD

**Issue by addonaddict** [xod-wow/LiteBag#12]
Works in previous versions back from september or so. Please fix. Thanks

**Comment by mbattersby** [comment]
I had to take this out in 9.1.5 because how it works conflicts with the new Item Upgrade interface Blizzard implemented. And not because of any bug of mine, because of taint and blizzard's UIDropDownMenu general crappiness.

I couldn't find any way around it without completely replacing the dropdown menu implementation. I'm aware it's no longer there but it will not return for months yet, until I have time to either do a substantial amount of work or delete LiteBag.

**Comment by mbattersby** [comment]
LiteBag 9.1.2 was the last version with the menu in it. If you are happy to disable/enable litebag every time you need to use the item upgrade NPC interface, you can keep using that version.

**Comment by addonaddict** [comment]
Thank you for the explanation

**Comment by mbattersby** [comment]
It makes me sad :(

**Comment by addonaddict** [comment]
Your addon is fantastic, this is a minor inconvenience. Thank you

**Comment by mbattersby** [comment]
I've tried fixing this using LibUIDropDownMenu. Can you please try 9.2.1.

**Comment by addonaddict** [comment]
Works like a charm so far with no errors! Thank you sooo much!!

**Comment by mbattersby** [comment]
You're welcome, going to close this off I think it's working with item upgrades too!
