### ISSUE TITLE
Moveable Bank (was Bank movement with DeModal support + icon thick borders requests)

### ISSUE THREAD

**Issue by Rezy942** [xod-wow/LiteBag#38]
Hello, love the addon!!!

See below:

1) When using DeModal, LiteBag FORCES bank to NOT move. (demodal allows movement of bank and many other frames).
Is there a chance you can allow DeModal to modify bank frame location?
It is very important especially for widescreen monitors like mine, as I really need it closer to center of my screen.
Disabling LiteBag allows me to move bank with DeModal. Enabling LiteBag resets position and locks it.

2) "thicker" icon borders are a bit TOO think. I want to use this feature but it turns the icons quite ugly.
Is it possible to reduce the thickness slightly or allow something of in-between?
Bagnon does it amazing as an example.

Thank you!

**Comment by mbattersby** [comment]
Bagnon
<img width="115" alt="image" src="https://user-images.githubusercontent.com/1300207/235572898-8f63bbdd-ab5f-4d68-8557-ae9457f316d1.png">

Litebag
<img width="149" alt="image" src="https://user-images.githubusercontent.com/1300207/235573013-b3050a9e-9e79-4d5a-bf8a-e0a1b934106e.png">

Blizzard
<img width="124" alt="image" src="https://user-images.githubusercontent.com/1300207/235573086-e4146e7c-fc22-48ac-86c1-f07b80dfb338.png">

**Comment by mbattersby** [comment]
Hi there. There's no way to make DeModal support LiteBag. It has a fixed list of Blizzard frames it supports, and that's it. I can see why, I mean I could make LiteBag support moveable bank, but I don't.

As far as the texture goes, I'm not at all convinced, see screenshot. Bagnon puts an overlay glow over the top (rather than change the actual border texture). I think the LiteBag one looks better and if it were any thinner it would just be the Blizzard default. It's not something that has a "this thick" slider, it's a square artwork of the outline put onto the button border.

I'm happy for you to try to change my mind some more, I could be wrong. But right now, I don't see it.

**Comment by mbattersby** [comment]
You can paste your own screenshots into this text box from the clipboard (windows-shift-s and drag or command-shift-4 on mac and drag, then paste).

**Comment by Rezy942** [comment]
Thank you for this texture comparison! I guess Bagnon's inner glow tricked my eyes into thinking it was different. (its been a while since i used bagnon). Perhaps that's why I liked it more. LiteBag's border thickness is the same but it may be the overpowering color-differences that make it stand out so much to me.
Here is my side-to-side comparison:
![image](https://user-images.githubusercontent.com/122007087/235807174-e2ab7562-db6f-417d-a40b-c50509a882a1.png)

I dont code so no idea if worth the effort but -
Would you consider adding a separate texture option to match Bagnon's? (I know some addons utilize pretty nice texture packs)
Or perhaps same texture but made like 20-30% less thick (for me blizz is way too thin, and LiteBag is a bit too thick, a middle ground would be fantastic)
All this is my opinion though that might not be shared, but for example my wife uses litebag and she too thinks its too thick that its distracting a bit. Havent asked anyone else really..


Reg. bank movement:
DeModal does support bank frame movement, but I guess LiteBag does something that prevents all movement and resets bank to default location. I tested this by only having DeModal -> moving bank -> turning on LiteBag -> bank resets & cant be moved.
Would you consider doing something to at least make LiteBag not do anything to frame movement so other addons can take contreol of it? 
Or perhaps add frame movement function to LiteBag bag & bank frames :)

Thanks!

**Comment by mbattersby** [comment]
Your bagnon example doesn't look any different to the Blizzard frames to me. Maybe it's my eyes that are tricked.

Obviously I like LiteBag how it is, I much prefer it thick and obvious and in your face. I think the Blizzard one is way too thin, I don't know why they didn't make it a tiny bit thicker too. Then that would be the middle ground and everyone would be happy.

Would I consider adding a textureoption? No, honestly I'm happy with it. I only have so much time and need to decide what to spend it on. I'd be happy if someone else did the work, I'd take it and include it, but who is going to do that? Even if I put your suggestion on the to-do list, it's never going to get to the top. I feel it's best to be up-front about it, sorry.

To some degree the thickness you want depends on how big you have the bag. The border size (because it's a texture) scales with the size of the button. It looks like you have the bag bigger than I do, maybe that's why it seems too thick for you. There's no way to say "the border is always 2 pixels no matter how big the frame is" (at least as far as I know).

With moving, it's not that LiteBag prevents the Blizzard bank moving, it completely replaces the bank. DeModal doesn't move it because it's not the Blizzard bank, it's LiteBag. It's completely separate and unrelated to the Blizzard bank frame. No DeModal option will affect it in any way, unless you hack DeModal to add LiteBagBank to the list of frames it handles.

LiteBag doesn't do anything to stop other addons moving it, I'm pretty sure something like MoveAnything and that kind of thing would move it just fine. DeModal just has a fixed list and it's only Blizzard's stuff.

You can obviously already move the bags frame. It's been a long-time design choice to have LiteBag put the bank in the same placed way Blizzard do it. I like it that way, as I'm sure you can guess. It's hard to have it do both (mostly because I had to do a lot of trickery to make it able to scale while using the Blizzard modal placement), so when it comes to choosing I obviously do what I prefer. I'll have another look at this some time but I'm guessing it wouldn't be for at least a month.

**Comment by Rezy942** [comment]
Thank you for the detailed explanation. My example on the right was blizzard, sorry!
The textures are not an issue, ill just stick with default blizz border.
I understand now about the bank movement. Unfortunately I use a wide screen so the bank is just too far away for me to comfortably use it for a long time (im AH goblin!)

This might become the breaking point for me after which i will either try to find a different move frame addon, or switch back to bagnon (i hate how overcomplicated it is)

Again, thank you!

**Comment by mbattersby** [comment]
In terms of the bank position, can you try this and see if it appears in a more central spot?
```
/run LiteBagBank:SetAttributeNoHandler("UIPanelLayout-area", "center")
```
I think the way Blizzard places the UI Panels the center area will prevent other frames from opening at the same time though.

**Comment by mbattersby** [comment]
Oops should be:
```
/run LiteBagBankPlacer:SetAttributeNoHandler("UIPanelLayout-area", "center")
```

**Comment by Rezy942** [comment]
Just tried it - it put the bank in a center position (yet still static)
Definetely better although creates an issue if user wants to "stretch" the bag to be longer horizontally
DeModal takes care of opening windows on top of each other though, so thats not an issue (in my case)

With this in mind - is it possible to add this as an addon option in bank section?
This way users can still get updates without re-entering the macro :)
Lastly not sure if possible as I dont code - but do you think X and Y offset will work in similar fashion?
Lets say currently frame is stuck in center of UI - then user offsets it by X amount of pixels?

Thanks :)

**Comment by mbattersby** [comment]
I'm still thinking about what the best thing to do is. Please be patient for a little while.

I don't think that "center" placement is good answer but I thought I'd as you, but you don't think it's a good answer either so that confirms it.

There's no x or y offset kind of thing with the Blizzard placed frames, the Blizzard handlers just put them where they decide.

**Comment by Rezy942** [comment]
No rush at all and definetely dont feel like you have to do anything about this!
I will still use LiteBag no matter what. The center position is actually much better for me than the original, so if x and y thing doesnt exist then perhaps option to "center" the bank is a good solution.

If you can come up with something better then by all means, but otherwise this is a great compromise :)

**Comment by mbattersby** [comment]
Are you able to try the beta release 10.1.0-2beta1?

It has a test version of moveable bank. I'm sure it has a lot of bugs, please try to break it.

**Comment by Rezy942** [comment]
Trying it on right now and so far it works flawlessly. Will test it further and let you know of any issues. (very excited!!!)


There (may) be a minor UI issue. I was able to reproduce it once, but after trying many many times I could not. Will test more soon. 
This issue is also present on a bank addon called "Combined Bank", although their issue is 100% constant, for LiteBag it isnt. You can easily see example of that if you enable their addon and try to move camera around close to bags area.

Issue: the old "ghost" bag frames (see screenshots below) despite being invisible, still retain their frame. So that when you try to move camera around or put your bank frame over those "ghost" frames - your cursor actually interacts with THOSE frames due to them being on top of everything else. Makes moving items around behind those frames impossible. (of course most users will never have their bank there - although UI scale and monitor size dependant!)

Explanation of which bag frames im talking about:
![image](https://user-images.githubusercontent.com/122007087/236656434-45a0a067-275e-4e45-aed8-c33dfc90104d.png)
 
Very rough and approximate example of what happens:
![image](https://user-images.githubusercontent.com/122007087/236656569-0387781c-e982-4f80-b10a-8179d2e345c8.png)

**Comment by Rezy942** [comment]
Also probably a non-issue but strange behavior - moving bank frame triggers bag frame to open.
Reproduce:
1. Open bank (both bag and bank will open)
2. Close bag frame
3. Move bank frame anywhere
4. Bag frame will re-open

Dont think this will affect anyone - but might cause some annoyances for those running something like TSM or other addon frames while operating bank? idk :)

**Comment by mbattersby** [comment]
Thanks, this is all very helpful. Please keep reporting issues I'll look at them when I have the time.

**Comment by mbattersby** [comment]
There is a second beta which hopefully fixes the "bag opens when moving bank" issue.

**Comment by Rezy942** [comment]
> There is a second beta which hopefully fixes the "bag opens when moving bank" issue.

Tested and works flawlessly!
Played for many hours (AH goblin style), tested many different interactions. I'd say its pretty stable - but only time will tell!

**Comment by mbattersby** [comment]
Sorry there will be a little bit of a pause on the moveable bank work while I look at the taint problems from the other issue.

**Comment by Rezy942** [comment]
No worries at all. Will keep an eye out and report. Thanks again for deciding to add this in :)

**Comment by mbattersby** [comment]
New beta version, 10.1.0-2beta3.

Few unrelated changes (move info button and lock/unlock to the drop-down menu), and hopefully also fixes the error at the dummy you mentioned. If you can test that error is really gone that would help a lot too.

**Comment by Rezy942** [comment]
Great, will test soon

**Comment by Rezy942** [comment]
Works great so far - no issues

**Comment by mbattersby** [comment]
Did it fix your target dummy addon blocked issue?

**Comment by Rezy942** [comment]
Yes ive tested that too! Works flawless!

**Comment by mbattersby** [comment]
Thanks, appreciate your help again!
