### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Rezy942** [xod-wow/LiteBag#40]
Hello,

I would like to request a few minor features:
![image](https://user-images.githubusercontent.com/122007087/235811591-a9287e2d-51cb-45f4-a95a-a3e39f16ed53.png)

1) Extend search box to edge of first bag slot (looks more neat imo)
2) Add option to HIDE the bag row as shown in red rectangle. Perhaps RIGHT CLICK on big icon at top left? Right is for menu.
This would be saved globally for all characters.
Imo its great for saving space and overall more neat interface :)
3) Option to remove the options button, or/and allow right clicking on title bar to open options.

Thank you :)

**Comment by mbattersby** [comment]
Hi, just letting you know with a new patch landing today I'll be busy (a) playing and (b) making sure my addons actually work.

In terms of your suggestions (thanks!), definitely won't be doing (3), and probably won't be doing (1) which is how Blizzard do it and I think it looks ok. I would like to do (2) but haven't been able to make it work, I'll probably have another go at some point.

I'll be realistic, LiteBag is like 8 years old, it's pretty much done. I'm not planning on making it into something else, and for the most part it works the way I like it. There's plenty of other bag addons out there for people who want different things.

**Comment by mbattersby** [comment]
I'm going to close this off, the one I'd like to do (2) is already covered by issue #28.

In an ideal world I'd like to have the search bar show next to the bag buttons if (a) they are shown and (b) there's enough space, and then otherwise below where it is. All of my attempts to get that to work so far were miserable failures.

Thanks again for your suggestions.

**Comment by Rezy942** [comment]
I see, thank you for the quick response and honesty. And im not aware if its popular or not, but yours is the only one my wife and my guild mates can stand using. Theres more of us than you might be aware of ;)

**Comment by Rezy942** [comment]
I just wanted to leave this link to bagnon thread with you: https://github.com/Jaliborc/Bagnon/issues/1659
Everyone is looking for bagnon alternative right now as author silently abandoned his projects without giving rights to edit.
Not sure if youre interested but maybe something to think about :)
LiteBag is amazing as it is, and with (optional) additions it can easily become the most used, such as:
-store and view alt inventory & bank
-movable bank frame :)
-similar visual design (as secondary option) when it comes to frame and icon glow as we discussed earlier. Bagnon visuals were a major sticking point imo.

But again, its your call, just wanted to bring up this development to you :)

**Comment by mbattersby** [comment]
I see there is a new bagnon release already, so crisis averted!

The author (jaliborc) tends to be a bit slow updating Bagnon every major patch, so I've seen this at least twice before where a heap of people come to LiteBag and start asking (sometimes politely, sometimes not) if I can please make it into Bagnon for them. Then when Bagnon is updated they all vanish again.

It doesn't really bother me (other than I tend to take patch-day requests with a grain of salt), but the reality is I don't have time to make Bagnon even if I wanted to. Every new feature seems small in isolation, but each one makes LiteBag 10% harder to maintain, and I'm basically at capacity already (since I have some semblance of a life, other addons I maintain, a job, and do actually enjoy playing WoW also). So I just stay mostly with what I want, and hope other people get something from it too.

**Comment by mbattersby** [comment]
Funny story but LiteBag only exists because Combuctor (and Bagnon, same author) was abandoned for several months in 2012 forcing me to write my own.
