### ISSUE TITLE
Cata Classic Feature Request: Search Bar

### ISSUE THREAD

**Issue by Clamsoda** [xod-wow/LiteBag#53]
Any plans to implement the search bar into the Cata Classic version?

Thanks.

**Comment by mbattersby** [comment]
No, sorry. The search box in LiteBag is the Blizzard one I just grab it and attach it to LiteBag. Since Classic doesn't have one, I'd have to write an entire search system from scratch and I don't have that kind of time, especially with TWW.

It's possible if you install this

https://www.curseforge.com/wow/addons/classic-bag-search-tbc

it will add a search box LiteBag will use. I'm curious if that works. If it does I could incorporate it into LiteBag pretty easily I think.

**Comment by mbattersby** [comment]
In the space of one comment the answer went from "definitely not" to "well, maybe I dunno". Haha

**Comment by Clamsoda** [comment]
Cataclysm Classic has bag search as a native feature.

**Comment by mbattersby** [comment]
Do enable it somehow?

![Uploading image.png…]()

**Comment by Clamsoda** [comment]
My apologies, it is a feature added by Leatrix Plus.  I should have been more thorough.  Sorry to waste your time.

**Comment by mbattersby** [comment]
Yep I see that, I'm adding one in myself. Thanks!

**Comment by mbattersby** [comment]
Search box enabled in 4.4.0-2-cata, please try it.

**Comment by Clamsoda** [comment]
Works perfect.

Thank you!
