### ISSUE TITLE
Accountwide saved variables instead of per character

### ISSUE THREAD

**Issue by pngmn** [xod-wow/LiteBag#6]
Is there a reason why the saved variables are stored per character?
In my opinion there aren't any options that I have to adjust per character.
Would it be possible to change this or add an option for it?

**Comment by mbattersby** [comment]
I'm not sure, it's been like that for 8 years now. I think it's probably because people want to have per-character settings and I don't want to put in profiles because that involves pulling in all these Ace library dependencies.

I'm not against the idea of a "per-character options" tickbox kind of thing, but I'll be honest. LiteBag is pretty much done, it's been in maintenance only for years now and I'm not sure I'm likely to add new things to it.
