### ISSUE TITLE
in combat bug default blizzard raid frame  if group size change 5+

### ISSUE THREAD

**Issue by D3ssyl** [xod-wow/LiteBag#9]
42x [ADDON_ACTION_BLOCKED] AddOn 'LiteBag' tried to call the protected function 'CompactRaidGroup1:unusedFunc()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `unusedFunc'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:160: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
Skipped (In Encounter)

**Comment by mbattersby** [comment]
Unfortunately this is a Blizzard bug with their drop down menu code, some variant on:

https://www.townlong-yak.com/bugs/Mx7CWN-RefreshOverread

that they haven't fixed in a long time. It's not necessarily even LiteBag that causes the issue, another addon can trigger it and make LiteBag take the blame in the output. LiteBag doesn't have any interaction with the CUF, it's all through the dropdown menu issues.

I've tried including that workaround but I guess it hasn't worked. You could try installing the https://www.townlong-yak.com/addons/taintless addon and see if that fixes it. I don't think there's anything I can do about it short of rewriting LiteBag to use my own or someone else's non-blizzard drop down menu code, and I really just won't have the time.
